Adds environment variables
melix/jmh-gradle-plugin pull request #212
Opened 2021-11-12 09:12 UTC by bric3

This proposed change is about the support of _environment variables_ when launching the jmh jar. (Because the `org.openjdk.jmh.annotations.Fork` don't allow to pass environments).

_The jmh block is of type `JmhParameters` and `WithJavaToolchain` so in order to support a similar API as `JavaExecSpec` it has to be explicitly exposed._

**Current alternative**
The currently API does not allow this so we have to executes the jmh jar outside gradle.

```shell
$ ./gradlew :jmh-panama:jmhJar
$ env JAVA_LIBRARY_PATH=$(grealpath jmh-panama/jni) \
  java -jar jmh-panama/build/libs/jmh-panama-jmh.jar \
  -jvmArgs '-Xms256m -Xmx256m -Djmh.separateClasspathJAR=true --add-modules=jdk.incubator.foreign --enable-native-access=ALL-UNNAMED'
```

**Note**
I didn't see a functional test with jmh options so I'm not sure how you'd want to test that.

2021-11-12 09:13 UTC, bric3 commented
I'd like something closer to the `JavaExecSpec`, but the `jmh` block is not extending it. 

```kotlin
environment(mapOf("JAVA_HOME" to System.getenv("JAVA_HOME")))
environment("JAVA_HOME", System.getenv("JAVA_HOME"))
```

And I am not sure how best to proceed. Same for the tests.

2022-03-28 14:40 UTC, bric3 commented
Wow I wonder how the PR description was empty, was it me that forgot 🤔🤦 ?
I just rebased this pr on the latest from master.

2022-03-28 14:43 UTC, melix requested changes
Would be great to have a test of some kind. Could be a benchmark which spits out an environment variable via `System.out` and that the test would search for in the output.

2022-03-28 15:30 UTC, bric3 commented on src/main/java/me/champeau/jmh/JMHTask.java
> +        ParameterConverter.collectEnvironment(this, env);
Fixed

2022-03-29 08:31 UTC, bric3 commented
> Would be great to have a test of some kind. Could be a benchmark which spits out an environment variable via System.out and that the test would search for in the output.

Done

2022-03-29 08:50 UTC, melix approved these changes
Great, thank you!

2022-03-29 13:18 UTC, merged